# Copyright 2026 Graeme Lawes
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI

on:
  push:
    branches: [main, master]
  pull_request:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    if: github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod
    - name: Lint
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      with:
        version: latest
        args: -v --timeout 5m --build-tags=e2e ./...
        skip-cache: true

  test:
    if: github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod
    - name: Test
      run: go test -v -race ./...

  e2e:
    if: github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
    - name: Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod
    - name: Install helm and kubectl
      run: |
        sudo snap install helm --classic
        sudo snap install kubectl --classic
    - name: Install kind
      run: go install sigs.k8s.io/kind@v0.33.0
    - name: Setup e2e
      run: make setup-e2e
    - name: Run e2e test
      run: make test-e2e
    - name: Teardown e2e test
      if: always()
      run: make teardown-e2e
